### ISSUE TITLE
The alpha of svg should be flipped in dark mode for socials svg

### ISSUE THREAD

**Issue by ShravanSunder** [scaffold-eth/buidlguidl-v3#8]
![image](https://user-images.githubusercontent.com/5294949/153523865-67f7c0fd-77e0-4bb6-bacf-53e0be6f97e6.png)

**Comment by carletex** [comment]
![image](https://user-images.githubusercontent.com/2486142/153559220-364be27c-e7c3-43c7-a57c-fdfff60f14d8.png)
