### ISSUE TITLE
Sand Garden display shows for both the old and new sand garden cohorts.

### ISSUE THREAD

**Issue by ZakGriffith** [scaffold-eth/buidlguidl-v3#87]
After the creation of the new Sand Garden, this is what is displaying when a builder is viewed.  This is also the case in the builder search. 

![image](https://github.com/scaffold-eth/buidlguidl-v3/assets/12072395/7d104795-1fd6-4548-92ce-5d4f9011967b)

**Comment by carletex** [comment]
Thanks for reporting @ZakGriffith ! 

Should be good now. We can keep an eye in case they re-appear (the indexer might be doing so funky stuff)
