### ISSUE TITLE
Access to Admin Route when Admin url is pasted on Address bar

### ISSUE THREAD

**Issue by ceeriil** [scaffold-eth/buidlguidl-v3#89]
Anyone can access the admin route by typing the URL into their browser's address bar, even if they are not authorized as admins. Although Interaction to Page is restricted, I think it's best if this page doesn't show at all to non admin.

<img width="1440" alt="Screenshot 2024-04-11 at 11 22 56" src="https://github.com/scaffold-eth/buidlguidl-v3/assets/84419154/489a7ae0-3ae9-4c43-9664-1641146701fd">

#### Steps to Reproduce
1. Pasting "https://app.buidlguidl.com/admin/add-builder" on address bar shows the admin page

#### Expected Behavior
Non-admin users should be redirected to the homepage when attempting to access the admin route through address bar

**Comment by carletex** [comment]
Thanks for this @ceeriil 

We are 100% aware of this, and it's not really an issue/priority since we don't hold any private data + you need to sign as an admin to make any write action.

In any case, if you want to make a PR (sweet & simple) that redirects to the homepage... more than welcome!
